export const productDB = [
  {
    id: 1,
    title: 'Storytelling Masterclass',
    shortDesc: 'This is a digital product',
    fullDesc:
      'Digital products are easy to sell because you do not need to handle physical inventory because everything is made and distributed online. So start selling your digital products with Khallio.',
    type: 'Course',
    revenue: '₦487k',
    orders: '218',
    amount: 12000,
    url: '',
    status: 'published',
  },
  {
    id: 2,
    title: 'Content Creator Ebook',
    shortDesc: 'This is a digital product',
    fullDesc:
      'Digital products are easy to sell because you do not need to handle physical inventory because everything is made and distributed online. So start selling your digital products with Khallio.',
    type: 'Ebook',
    revenue: '₦487k',
    orders: '218',
    amount: 12000,
    url: '',
    status: 'draft',
  },
  {
    id: 3,
    title: 'Social Media Templates',
    shortDesc: 'This is a digital product',
    fullDesc:
      'Digital products are easy to sell because you do not need to handle physical inventory because everything is made and distributed online. So start selling your digital products with Khallio.',
    type: 'Course',
    revenue: '₦500k',
    orders: '218',
    amount: 12000,
    url: '',
    status: 'published',
  },
  {
    id: 4,
    title: 'Brand Voice Guide',
    shortDesc: 'This is a digital product',
    fullDesc:
      'Digital products are easy to sell because you do not need to handle physical inventory because everything is made and distributed online. So start selling your digital products with Khallio.',
    type: 'Ebook',
    revenue: '₦487k',
    orders: '218',
    amount: 12000,
    url: '',
    status: 'draft',
  },
  {
    id: 5,
    title: 'Video Script Pace',
    shortDesc: 'This is a digital product',
    fullDesc:
      'Digital products are easy to sell because you do not need to handle physical inventory because everything is made and distributed online. So start selling your digital products with Khallio.',
    type: 'Template',
    revenue: '₦487k',
    orders: '218',
    amount: 12000,
    url: '',
    status: 'published',
  },
  {
    id: 6,
    title: 'Creator OS Template',
    shortDesc: 'This is a digital product',
    fullDesc:
      'Digital products are easy to sell because you do not need to handle physical inventory because everything is made and distributed online. So start selling your digital products with Khallio.',
    type: 'Template',
    revenue: '₦487k',
    orders: '218',
    amount: 12000,
    url: '',
    status: 'draft',
  },
  {
    id: 7,
    title: 'YouTube Growth Checklist',
    shortDesc: 'This is a digital product',
    fullDesc:
      'Digital products are easy to sell because you do not need to handle physical inventory because everything is made and distributed online. So start selling your digital products with Khallio.',
    type: 'Ebook',
    revenue: '₦487k',
    orders: '218',
    amount: 12000,
    url: '',
    status: 'published',
  },
  {
    id: 8,
    title: 'Podcast Launch ToolKit',
    shortDesc: 'This is a digital product',
    fullDesc:
      'Digital products are easy to sell because you do not need to handle physical inventory because everything is made and distributed online. So start selling your digital products with Khallio.',
    type: 'Course',
    revenue: '₦487k',
    orders: '218',
    amount: 12000,
    url: '',
    status: 'published',
  },
];
